version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  cicd-job:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: install dependencies - NPM packages
          command: npm install

      - run:
          name: Run linter
          command: npm run linter
      - run:
          name: CD - Deploy the service
          command: curl "https://api.render.com/deploy/srv-ch00940rddlaqj0fl45g?key=JZzaNvrIMs4"

workflows:
  cicd-workflow:
    jobs:
      - cicd-job
