name: Continuous Integration
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies - NPM packages
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Run linter
        run: npm run lint

      - name: Deploy to production
        run: curl "https://api.render.com/deploy/srv-cglcae8rddleudrb2ju0?key=h1yshQzqiOU"
